Add retry to rtm.connect
toptal/xene pull request #43
Opened 2023-10-25 10:26 UTC by mbie

2023-10-30 07:43 UTC, sasha370 commented on packages/slack/src/api/base/request.ts
> +type Task = { uri: string, form: any, token: string, retryable: boolean, resolve: Callback, reject: Callback }
Can we move it to Types? https://github.com/toptal/xene/blob/master/packages/slack/src/types.ts

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/base/request.ts
> +      logger.info('Slack API rate limited for %s ms', delay)
```suggestion
      logger.info('Slack API rate limited for %sms', delay)
```

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/base/request.ts
> +      logger.info('Slack API timeout: %s. Retrying in %s ms', error.cause.code, delay)
```suggestion
      logger.info('Slack API timeout: %s. Retrying in %sms', error.cause.code, delay)
```

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/base/request.ts
> +const DEFAULT_RETRY_AFTER = 10 * 1000 // 10 seconds
```suggestion
const DEFAULT_RETRY_AFTER = 10 * 1000 // miliseconds
```

I'd suggest to rather specify unit than restating value

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/base/request.ts
> +    let retryableCodes = ['ETIMEDOUT', 'ESOCKETTIMEDOUT', 'EHOSTUNREACH', 'ECONNREFUSED']
Can we defined it as constant once?

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/rtm/index.ts
> +    logger.verbose('Configuring websocket connection to %s', response.url)
```suggestion
    logger.verbose('Configuring WebSocket connection to %s', response.url)
```

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/base/request.ts
> +      const delay = DEFAULT_RETRY_AFTER
```suggestion
```

Looks that it's assigned to get around line length limitation.
WDYT on wrapping

```
logger.info(
  ...
)
```

Especially that `retryRequest` references `DEFAULT_RETRY_AFTER`

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/base/request.ts
> +      const delay = Number(error.response.headers['retry-after']) * 1000
```suggestion
      const delayInMs = Number(error.response.headers['retry-after']) * 1000
```

That's how `retryRequest` names it. Can we keep the same?

2023-10-30 10:25 UTC, kml commented on packages/slack/src/api/base/request.ts
> +const retryRequest = (task: Task, delay?: number) => {
```suggestion
const retryRequest = (task: Task, delayInMs?: number) => {
```

Would be helfpfull to see unit suffix in method signature

2023-10-30 11:15 UTC, id-ilych requested changes

2023-10-30 11:15 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +export const request = (uri: string, form: any, token: string, retryable: boolean = false) =>
Unnamed (non-keyword) boolean arguments are confusing. How about making it `options` with `retriable` field or even changing the whole arguments list to object/keyword?

2023-10-30 11:15 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +      const delay = Number(error.response.headers['retry-after']) * 1000
The header is:
- optional: [A `Retry-After` header **might** be included](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) (when missing use `DEFAULT_RETRY_DELAY_MS`)
- [not necessarily will contain a number of seconds](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) (have to handle both formats)

2023-10-30 11:15 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +      return done()
Why is `done` called here if request is being retried so the outcome is not known yet?

2023-10-30 11:15 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +      return done()
Why is `done` called here if request is being retried so the outcome is not known yet?

2023-11-02 11:33 UTC, mbie commented on packages/slack/src/api/base/request.ts
> +      retryRequest(task, DEFAULT_RETRY_AFTER)
yeah, not sure why I did not use it here.

2023-11-02 11:43 UTC, mbie commented on packages/slack/src/api/base/request.ts
> +export const request = (uri: string, form: any, token: string, retryable: boolean = false) =>
I agree that they are confusing, but I wanted to have as less code changes/simplest as possible here

2023-11-02 11:47 UTC, mbie commented on packages/slack/src/api/base/request.ts
> +      return done()
The previous implementation called `done` in case of retry as well. I spent some time once I realized that. Without the `done` the queue got stuck so I needed to add it explicitly

2023-11-02 17:13 UTC, mbie commented on packages/slack/src/api/base/request.ts
> +      const delay = Number(error.response.headers['retry-after']) * 1000
This was the initial implementation, I did not change it and it was working fine before.

2023-11-03 05:01 UTC, sasha370 approved these changes

2023-11-03 08:02 UTC, kml approved these changes
LGTM

2023-11-03 10:16 UTC, id-ilych approved these changes

2023-11-03 10:16 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +    return task.reject(error)
I might be wrong but it looks like `done` should be called regardless of the outcome no to block the queue worker. I suggest removing early returns (replacing with if-else if-else) and call `done` as the last line.

2023-11-03 10:16 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +  setTimeout(queue.resume, delayInMs)
```suggestion
const retryRequest = (task: Task, delayMs: number) => {
  setTimeout(queue.resume, delayMs)
```

2023-11-03 10:16 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +    await rp.post({ uri: task.uri, json: true, form: task.form, headers, timeout: REQUEST_TIMEOUT }).then(task.resolve)
```suggestion
    const result = await rp.post({ uri: task.uri, json: true, form: task.form, headers, timeout: REQUEST_TIMEOUT })
    task.resolve(result)
```

2023-11-03 10:18 UTC, id-ilych commented on packages/slack/src/api/base/request.ts
> +      const delayMs = Number(error.response.headers['retry-after']) * 1000
```suggestion
      const delayMs = (Number(error.response.headers['retry-after']) * 1000) || DEFAULT_RETRY_DELAY_MS
```

2023-11-03 10:24 UTC, mbie commented on packages/slack/src/api/base/request.ts
> +    return task.reject(error)
With the initial implementation `done` was outside `try.catch` block. I will restore it there.

2023-11-03 12:41 UTC, merged